In [4]:
import pandas as pd
import numpy as np  
df = pd.DataFrame({
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["HR", "IT", "HR", "IT", "Finance", "Finance", "HR", "IT"],
    "Gender": ["F", "M", "M", "M", "F", "M", "F", "M"],
    "Salary": [50000, 70000, 55000, 65000, 60000, 62000, 58000, 72000],
    "Experience": [2, 5, 3, 4, 6, 2, 4, 7]
})

print(df)

  Employee Department Gender  Salary  Experience
0    Alice         HR      F   50000           2
1      Bob         IT      M   70000           5
2  Charlie         HR      M   55000           3
3    David         IT      M   65000           4
4      Eva    Finance      F   60000           6
5    Frank    Finance      M   62000           2
6    Grace         HR      F   58000           4
7    Henry         IT      M   72000           7

In [5]:
pd.pivot_table(df,values='Salary',index="Gender", columns="Department")

Department  Finance       HR       IT
Gender
F           60000.0  54000.0      NaN
M           62000.0  55000.0  69000.0

In [10]:
#crosstab
pd.crosstab(df["Gender"],df["Department"])

Department  Finance  HR  IT
Gender
F                 1   2   0
M                 1   1   3